name: learn-github-actions
on:
  push:
    branches:
      - smashpunk-patch-1
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo ${{ secrets.YOUR_NAME}}
